// @ts-nocheck
/**
 * BillQRCode Component
 * Displays QR code for customer self-payment
 * SECURITY: Sanitizes all user-generated content to prevent XSS attacks
 */

import { QRCodeSVG } from 'qrcode.react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { QrCode, Download, Printer } from 'lucide-react';
import type { BillResponse } from '@/types/bills';
import { sanitizePlainText } from '@/lib/security/sanitize';

interface BillQRCodeProps {
  bill: BillResponse;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function BillQRCode({ bill, open, onOpenChange }: BillQRCodeProps) {
  // Generate payment URL that customers will scan
  const paymentUrl = `${window.location.origin}/pay/${bill.bill_number}`;

  const handleDownloadQR = () => {
    const canvas = document.getElementById('bill-qr-code') as HTMLCanvasElement;
    if (!canvas) return;

    const svg = canvas.querySelector('svg');
    if (!svg) return;

    const svgData = new XMLSerializer().serializeToString(svg);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const svgUrl = URL.createObjectURL(svgBlob);

    const downloadLink = document.createElement('a');
    downloadLink.href = svgUrl;
    downloadLink.download = `bill-${bill.bill_number}-qr.svg`;
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);
    URL.revokeObjectURL(svgUrl);
  };

  const handlePrintQR = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    // SECURITY FIX: Sanitize all user-generated content to prevent XSS
    const safeBillNumber = sanitizePlainText(bill.bill_number);
    const safeTableNumber = bill.table_number ? sanitizePlainText(String(bill.table_number)) : '';
    const safeRoomNumber = bill.room_number ? sanitizePlainText(String(bill.room_number)) : '';
    const safeCustomerName = bill.customer_name ? sanitizePlainText(bill.customer_name) : '';
    const safeTotalAmount = Number(bill.total_amount).toLocaleString(); // Numbers are safe

    // Get QR code HTML (already safe - generated by library)
    const qrCodeHtml = document.getElementById('bill-qr-code')?.innerHTML || '';

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Bill ${safeBillNumber} - QR Code</title>
          <style>
            * { box-sizing: border-box; margin: 0; padding: 0; }
            body {
              font-family: 'Courier New', Courier, monospace;
              font-size: 12px;
              width: 280px;
              margin: 0 auto;
              padding: 8px;
              color: #000;
              text-align: center;
            }
            .bold { font-weight: bold; }
            .divider { border-top: 1px dashed #000; margin: 6px 0; }
            .divider-solid { border-top: 2px solid #000; margin: 6px 0; }
            .amount { font-size: 16px; font-weight: bold; margin: 8px 0; }
            .small { font-size: 10px; }
            .qr-wrap { margin: 10px 0; }
            .qr-wrap svg { width: 160px !important; height: 160px !important; }
            .steps { text-align: left; font-size: 11px; margin-top: 6px; }
            .steps li { margin: 2px 0 2px 14px; }
            @media print {
              @page { size: 80mm auto; margin: 0; }
              body { padding: 4px; }
            }
          </style>
        </head>
        <body>
          <div class="bold" style="font-size:15px;">Premier Hotel</div>
          <div class="bold" style="font-size:13px;margin-top:2px;">SCAN TO PAY</div>
          <div class="divider-solid"></div>

          <div><strong>Bill #:</strong> ${safeBillNumber}</div>
          <div><strong>Location:</strong> ${bill.location_type === 'table' ? `Table ${safeTableNumber}` : `Room ${safeRoomNumber}`}</div>
          ${safeCustomerName ? `<div><strong>Customer:</strong> ${safeCustomerName}</div>` : ''}

          <div class="divider"></div>
          <div class="amount">KES ${safeTotalAmount}</div>
          <div class="divider"></div>

          <div class="qr-wrap">${qrCodeHtml}</div>

          <div class="divider"></div>
          <div class="bold small">How to Pay:</div>
          <ol class="steps">
            <li>Open camera or QR scanner</li>
            <li>Scan the code above</li>
            <li>Choose M-Pesa or Card</li>
            <li>Complete payment</li>
          </ol>
          <div class="divider"></div>
          <div class="small">Need help? Ask our staff</div>

          <script>
            window.onload = function() {
              setTimeout(function() { window.print(); }, 500);
            };
          </script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat('en-KE', {
      style: 'currency',
      currency: 'KES',
    }).format(value);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <QrCode className="h-5 w-5" />
            Payment QR Code
          </DialogTitle>
          <DialogDescription>
            Customer can scan this QR code to pay the bill
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          {/* QR Code Display */}
          <div className="flex flex-col items-center justify-center p-6 bg-gray-50 rounded-lg">
            <div id="bill-qr-code" className="bg-white p-4 rounded-lg shadow-sm">
              <QRCodeSVG
                value={paymentUrl}
                size={200}
                level="H"
                includeMargin={true}
                bgColor="#ffffff"
                fgColor="#000000"
              />
            </div>
          </div>

          {/* Bill Info */}
          <Card>
            <CardContent className="pt-6 space-y-2">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Bill Number:</span>
                <span className="font-medium">{bill.bill_number}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Location:</span>
                <span className="font-medium">
                  {bill.location_type === 'table'
                    ? `Table ${bill.table_number}`
                    : `Room ${bill.room_number}`}
                </span>
              </div>
              <div className="flex justify-between text-lg font-bold border-t pt-2">
                <span>Amount:</span>
                <span className="text-primary">{formatCurrency(bill.total_amount)}</span>
              </div>
            </CardContent>
          </Card>

          {/* Instructions */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
            <h4 className="font-semibold text-sm mb-2 text-blue-900">
              How customers can pay:
            </h4>
            <ol className="text-xs text-blue-800 space-y-1 list-decimal list-inside">
              <li>Scan the QR code with phone camera</li>
              <li>Opens secure payment page</li>
              <li>Choose M-Pesa or Card payment</li>
              <li>Complete payment - no login required!</li>
            </ol>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-2">
            <Button onClick={handleDownloadQR} variant="outline" className="flex-1">
              <Download className="h-4 w-4 mr-2" />
              Download
            </Button>
            <Button onClick={handlePrintQR} variant="outline" className="flex-1">
              <Printer className="h-4 w-4 mr-2" />
              Print
            </Button>
          </div>

          {/* Payment URL (for copying) */}
          <div className="space-y-2">
            <label className="text-xs text-muted-foreground">Payment Link:</label>
            <div className="flex gap-2">
              <input
                type="text"
                value={paymentUrl}
                readOnly
                className="flex-1 px-3 py-2 text-xs border rounded-md bg-gray-50"
              />
              <Button
                size="sm"
                variant="outline"
                onClick={() => {
                  navigator.clipboard.writeText(paymentUrl);
                  alert('Link copied!');
                }}
              >
                Copy
              </Button>
            </div>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}
